// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: System.Net.HttpListenerRequest
#include "System/Net/HttpListenerRequest.hpp"
// Including type: System.Net.CookieCollection
#include "System/Net/CookieCollection.hpp"
// Including type: System.Net.WebHeaderCollection
#include "System/Net/WebHeaderCollection.hpp"
// Including type: System.IO.Stream
#include "System/IO/Stream.hpp"
// Including type: System.Version
#include "System/Version.hpp"
// Including type: System.Collections.Specialized.NameValueCollection
#include "System/Collections/Specialized/NameValueCollection.hpp"
// Including type: System.Uri
#include "System/Uri.hpp"
// Including type: System.Net.HttpListenerContext
#include "System/Net/HttpListenerContext.hpp"
// Including type: System.Net.IPEndPoint
#include "System/Net/IPEndPoint.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated static field getter
// Get static field: static private System.Byte[] _100continue
::Array<uint8_t>* System::Net::HttpListenerRequest::_get__100continue() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<::Array<uint8_t>*>("System.Net", "HttpListenerRequest", "_100continue"));
}
// Autogenerated static field setter
// Set static field: static private System.Byte[] _100continue
void System::Net::HttpListenerRequest::_set__100continue(::Array<uint8_t>* value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Net", "HttpListenerRequest", "_100continue", value));
}
// Autogenerated static field getter
// Get static field: static private System.Char[] separators
::Array<::Il2CppChar>* System::Net::HttpListenerRequest::_get_separators() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<::Array<::Il2CppChar>*>("System.Net", "HttpListenerRequest", "separators"));
}
// Autogenerated static field setter
// Set static field: static private System.Char[] separators
void System::Net::HttpListenerRequest::_set_separators(::Array<::Il2CppChar>* value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Net", "HttpListenerRequest", "separators", value));
}
// Autogenerated method: System.Net.HttpListenerRequest..ctor
System::Net::HttpListenerRequest* System::Net::HttpListenerRequest::New_ctor(System::Net::HttpListenerContext* context) {
  return THROW_UNLESS(il2cpp_utils::New<HttpListenerRequest*>(context));
}
// Autogenerated method: System.Net.HttpListenerRequest.SetRequestLine
void System::Net::HttpListenerRequest::SetRequestLine(::Il2CppString* req) {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "SetRequestLine", req));
}
// Autogenerated method: System.Net.HttpListenerRequest.CreateQueryString
void System::Net::HttpListenerRequest::CreateQueryString(::Il2CppString* query) {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "CreateQueryString", query));
}
// Autogenerated method: System.Net.HttpListenerRequest.MaybeUri
bool System::Net::HttpListenerRequest::MaybeUri(::Il2CppString* s) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>("System.Net", "HttpListenerRequest", "MaybeUri", s));
}
// Autogenerated method: System.Net.HttpListenerRequest.IsPredefinedScheme
bool System::Net::HttpListenerRequest::IsPredefinedScheme(::Il2CppString* scheme) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>("System.Net", "HttpListenerRequest", "IsPredefinedScheme", scheme));
}
// Autogenerated method: System.Net.HttpListenerRequest.FinishInitialization
void System::Net::HttpListenerRequest::FinishInitialization() {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "FinishInitialization"));
}
// Autogenerated method: System.Net.HttpListenerRequest.Unquote
::Il2CppString* System::Net::HttpListenerRequest::Unquote(::Il2CppString* str) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Il2CppString*>("System.Net", "HttpListenerRequest", "Unquote", str));
}
// Autogenerated method: System.Net.HttpListenerRequest.AddHeader
void System::Net::HttpListenerRequest::AddHeader(::Il2CppString* header) {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "AddHeader", header));
}
// Autogenerated method: System.Net.HttpListenerRequest.FlushInput
bool System::Net::HttpListenerRequest::FlushInput() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>(this, "FlushInput"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_HasEntityBody
bool System::Net::HttpListenerRequest::get_HasEntityBody() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>(this, "get_HasEntityBody"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_Headers
System::Collections::Specialized::NameValueCollection* System::Net::HttpListenerRequest::get_Headers() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::Collections::Specialized::NameValueCollection*>(this, "get_Headers"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_InputStream
System::IO::Stream* System::Net::HttpListenerRequest::get_InputStream() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::IO::Stream*>(this, "get_InputStream"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_IsSecureConnection
bool System::Net::HttpListenerRequest::get_IsSecureConnection() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>(this, "get_IsSecureConnection"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_KeepAlive
bool System::Net::HttpListenerRequest::get_KeepAlive() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<bool>(this, "get_KeepAlive"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_LocalEndPoint
System::Net::IPEndPoint* System::Net::HttpListenerRequest::get_LocalEndPoint() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::Net::IPEndPoint*>(this, "get_LocalEndPoint"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_ProtocolVersion
System::Version* System::Net::HttpListenerRequest::get_ProtocolVersion() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::Version*>(this, "get_ProtocolVersion"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_Url
System::Uri* System::Net::HttpListenerRequest::get_Url() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::Uri*>(this, "get_Url"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_UserHostAddress
::Il2CppString* System::Net::HttpListenerRequest::get_UserHostAddress() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Il2CppString*>(this, "get_UserHostAddress"));
}
// Autogenerated method: System.Net.HttpListenerRequest.get_UserHostName
::Il2CppString* System::Net::HttpListenerRequest::get_UserHostName() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Il2CppString*>(this, "get_UserHostName"));
}
// Autogenerated method: System.Net.HttpListenerRequest..cctor
void System::Net::HttpListenerRequest::_cctor() {
  THROW_UNLESS(il2cpp_utils::RunMethod("System.Net", "HttpListenerRequest", ".cctor"));
}
