// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: System.Xml.ElementProperties
#include "System/Xml/ElementProperties.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties DEFAULT
System::Xml::ElementProperties System::Xml::ElementProperties::_get_DEFAULT() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "DEFAULT"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties DEFAULT
void System::Xml::ElementProperties::_set_DEFAULT(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "DEFAULT", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties URI_PARENT
System::Xml::ElementProperties System::Xml::ElementProperties::_get_URI_PARENT() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "URI_PARENT"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties URI_PARENT
void System::Xml::ElementProperties::_set_URI_PARENT(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "URI_PARENT", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties BOOL_PARENT
System::Xml::ElementProperties System::Xml::ElementProperties::_get_BOOL_PARENT() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "BOOL_PARENT"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties BOOL_PARENT
void System::Xml::ElementProperties::_set_BOOL_PARENT(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "BOOL_PARENT", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties NAME_PARENT
System::Xml::ElementProperties System::Xml::ElementProperties::_get_NAME_PARENT() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "NAME_PARENT"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties NAME_PARENT
void System::Xml::ElementProperties::_set_NAME_PARENT(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "NAME_PARENT", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties EMPTY
System::Xml::ElementProperties System::Xml::ElementProperties::_get_EMPTY() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "EMPTY"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties EMPTY
void System::Xml::ElementProperties::_set_EMPTY(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "EMPTY", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties NO_ENTITIES
System::Xml::ElementProperties System::Xml::ElementProperties::_get_NO_ENTITIES() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "NO_ENTITIES"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties NO_ENTITIES
void System::Xml::ElementProperties::_set_NO_ENTITIES(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "NO_ENTITIES", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties HEAD
System::Xml::ElementProperties System::Xml::ElementProperties::_get_HEAD() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "HEAD"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties HEAD
void System::Xml::ElementProperties::_set_HEAD(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "HEAD", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties BLOCK_WS
System::Xml::ElementProperties System::Xml::ElementProperties::_get_BLOCK_WS() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "BLOCK_WS"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties BLOCK_WS
void System::Xml::ElementProperties::_set_BLOCK_WS(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "BLOCK_WS", value));
}
// Autogenerated static field getter
// Get static field: static public System.Xml.ElementProperties HAS_NS
System::Xml::ElementProperties System::Xml::ElementProperties::_get_HAS_NS() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::Xml::ElementProperties>("System.Xml", "ElementProperties", "HAS_NS"));
}
// Autogenerated static field setter
// Set static field: static public System.Xml.ElementProperties HAS_NS
void System::Xml::ElementProperties::_set_HAS_NS(System::Xml::ElementProperties value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.Xml", "ElementProperties", "HAS_NS", value));
}
