#pragma once
#include "UnityEngine/ResourceManagement/AsyncOperations/zzzz__InitalizationObjectsOperation_def.hpp"
#include "UnityEngine/ResourceManagement/AsyncOperations/zzzz__InitalizationObjectsOperation_impl.hpp"
