// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: System.IntPtr
#include "System/IntPtr.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine::LowLevel
namespace UnityEngine::LowLevel {
}
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Type
  class Type;
}
// Completed forward declares
// Begin il2cpp-utils forward declares
template<class T>
struct Array;
// Completed il2cpp-utils forward declares
// Type namespace: UnityEngine.LowLevel
namespace UnityEngine::LowLevel {
  // Autogenerated type: UnityEngine.LowLevel.PlayerLoopSystem
  struct PlayerLoopSystem : public System::ValueType {
    public:
    // Nested type: UnityEngine::LowLevel::PlayerLoopSystem::UpdateFunction
    class UpdateFunction;
    // public System.Type type
    // Offset: 0x0
    System::Type* type;
    // public UnityEngine.LowLevel.PlayerLoopSystem[] subSystemList
    // Offset: 0x8
    ::Array<UnityEngine::LowLevel::PlayerLoopSystem>* subSystemList;
    // public UnityEngine.LowLevel.PlayerLoopSystem/UpdateFunction updateDelegate
    // Offset: 0x10
    UnityEngine::LowLevel::PlayerLoopSystem::UpdateFunction* updateDelegate;
    // public System.IntPtr updateFunction
    // Offset: 0x18
    System::IntPtr updateFunction;
    // public System.IntPtr loopConditionFunction
    // Offset: 0x20
    System::IntPtr loopConditionFunction;
    // Creating value type constructor for type: PlayerLoopSystem
    constexpr PlayerLoopSystem(System::Type* type_ = {}, ::Array<UnityEngine::LowLevel::PlayerLoopSystem>* subSystemList_ = {}, UnityEngine::LowLevel::PlayerLoopSystem::UpdateFunction* updateDelegate_ = {}, System::IntPtr updateFunction_ = {}, System::IntPtr loopConditionFunction_ = {}) noexcept : type{type_}, subSystemList{subSystemList_}, updateDelegate{updateDelegate_}, updateFunction{updateFunction_}, loopConditionFunction{loopConditionFunction_} {}
  }; // UnityEngine.LowLevel.PlayerLoopSystem
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::LowLevel::PlayerLoopSystem, "UnityEngine.LowLevel", "PlayerLoopSystem");
#pragma pack(pop)
