#pragma once
#include "UnityEngine/AddressableAssets/Initialization/zzzz__AddressablesRuntimeProperties_def.hpp"
#include "UnityEngine/AddressableAssets/Initialization/zzzz__AddressablesRuntimeProperties_impl.hpp"
