// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Completed includes
// Type namespace: UnityEngine.Profiling
namespace UnityEngine::Profiling {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: UnityEngine.Profiling.Profiler
  // [TokenAttribute] Offset: FFFFFFFF
  // [NativeHeaderAttribute] Offset: D7E684
  // [NativeHeaderAttribute] Offset: D7E684
  // [UsedByNativeCodeAttribute] Offset: D7E684
  // [MovedFromAttribute] Offset: D7E684
  // [NativeHeaderAttribute] Offset: D7E684
  // [NativeHeaderAttribute] Offset: D7E684
  // [NativeHeaderAttribute] Offset: D7E684
  class Profiler : public ::Il2CppObject {
    public:
    // Creating value type constructor for type: Profiler
    Profiler() noexcept {}
    // static public System.Int64 GetMonoUsedSizeLong()
    // Offset: 0x1C747C0
    static int64_t GetMonoUsedSizeLong();
  }; // UnityEngine.Profiling.Profiler
  #pragma pack(pop)
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::Profiling::Profiler*, "UnityEngine.Profiling", "Profiler");
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: UnityEngine::Profiling::Profiler::GetMonoUsedSizeLong
// Il2CppName: GetMonoUsedSizeLong
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int64_t (*)()>(&UnityEngine::Profiling::Profiler::GetMonoUsedSizeLong)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(UnityEngine::Profiling::Profiler*), "GetMonoUsedSizeLong", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
