#pragma once
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundColorsGradientElementWithLightId_def.hpp"
#include "GlobalNamespace/zzzz__BloomPrePassBackgroundColorsGradientElementWithLightId_impl.hpp"
