// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: LevelFilteringNavigationController
#include "GlobalNamespace/LevelFilteringNavigationController.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: GlobalNamespace
namespace GlobalNamespace {
  // Forward declaring type: IBeatmapLevelPack
  class IBeatmapLevelPack;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0);
DEFINE_IL2CPP_ARG_TYPE(::GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0*, "", "LevelFilteringNavigationController/<>c__DisplayClass53_0");
// Type namespace: 
namespace GlobalNamespace {
  // Size: 0x18
  #pragma pack(push, 1)
  // Autogenerated type: LevelFilteringNavigationController/<>c__DisplayClass53_0
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: FFFFFFFF
  class LevelFilteringNavigationController::$$c__DisplayClass53_0 : public ::Il2CppObject {
    public:
    #ifdef USE_CODEGEN_FIELDS
    public:
    #else
    #ifdef CODEGEN_FIELD_ACCESSIBILITY
    CODEGEN_FIELD_ACCESSIBILITY:
    #else
    protected:
    #endif
    #endif
    // public IBeatmapLevelPack levelPack
    // Size: 0x8
    // Offset: 0x10
    ::GlobalNamespace::IBeatmapLevelPack* levelPack;
    // Field size check
    static_assert(sizeof(::GlobalNamespace::IBeatmapLevelPack*) == 0x8);
    public:
    // Creating conversion operator: operator ::GlobalNamespace::IBeatmapLevelPack*
    constexpr operator ::GlobalNamespace::IBeatmapLevelPack*() const noexcept {
      return levelPack;
    }
    // Get instance field reference: public IBeatmapLevelPack levelPack
    ::GlobalNamespace::IBeatmapLevelPack*& dyn_levelPack();
    // System.Boolean <SelectAnnotatedBeatmapLevelCollection>b__1(System.String packID)
    // Offset: 0x14AF200
    bool $SelectAnnotatedBeatmapLevelCollection$b__1(::StringW packID);
    // public System.Void .ctor()
    // Offset: 0x14AEF18
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static LevelFilteringNavigationController::$$c__DisplayClass53_0* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<LevelFilteringNavigationController::$$c__DisplayClass53_0*, creationType>()));
    }
  }; // LevelFilteringNavigationController/<>c__DisplayClass53_0
  #pragma pack(pop)
  static check_size<sizeof(LevelFilteringNavigationController::$$c__DisplayClass53_0), 16 + sizeof(::GlobalNamespace::IBeatmapLevelPack*)> __GlobalNamespace_LevelFilteringNavigationController_$$c__DisplayClass53_0SizeCheck;
  static_assert(sizeof(LevelFilteringNavigationController::$$c__DisplayClass53_0) == 0x18);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0::$SelectAnnotatedBeatmapLevelCollection$b__1
// Il2CppName: <SelectAnnotatedBeatmapLevelCollection>b__1
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0::*)(::StringW)>(&GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0::$SelectAnnotatedBeatmapLevelCollection$b__1)> {
  static const MethodInfo* get() {
    static auto* packID = &::il2cpp_utils::GetClassFromName("System", "String")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0*), "<SelectAnnotatedBeatmapLevelCollection>b__1", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{packID});
  }
};
// Writing MetadataGetter for method: GlobalNamespace::LevelFilteringNavigationController::$$c__DisplayClass53_0::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
