// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: OVRPlugin
#include "GlobalNamespace/OVRPlugin.hpp"
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: OVRPlugin/Vector2f
#include "GlobalNamespace/OVRPlugin_Vector2f.hpp"
// Including type: OVRPlugin/Sizef
#include "GlobalNamespace/OVRPlugin_Sizef.hpp"
// Completed includes
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRPlugin/Rectf
  struct OVRPlugin::Rectf : public System::ValueType {
    public:
    // private OVRPlugin/Vector2f Pos
    // Offset: 0x0
    GlobalNamespace::OVRPlugin::Vector2f Pos;
    // private OVRPlugin/Sizef Size
    // Offset: 0x8
    GlobalNamespace::OVRPlugin::Sizef Size;
    // Creating value type constructor for type: Rectf
    constexpr Rectf(GlobalNamespace::OVRPlugin::Vector2f Pos_ = {}, GlobalNamespace::OVRPlugin::Sizef Size_ = {}) noexcept : Pos{Pos_}, Size{Size_} {}
  }; // OVRPlugin/Rectf
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRPlugin::Rectf, "", "OVRPlugin/Rectf");
#pragma pack(pop)
