#pragma once
#include "UnityEngine/Android/AndroidAssetPackError.hpp"
#include "UnityEngine/Android/AndroidAssetPackInfo.hpp"
#include "UnityEngine/Android/AndroidAssetPackState.hpp"
#include "UnityEngine/Android/AndroidAssetPackStatus.hpp"
#include "UnityEngine/Android/AndroidAssetPackUseMobileDataRequestResult.hpp"
#include "UnityEngine/Android/AndroidAssetPacks.hpp"
#include "UnityEngine/Android/Permission.hpp"
#include "UnityEngine/Android/PermissionCallbacks.hpp"