#pragma once
#include "UnityEngine/ResourceManagement/ResourceProviders/zzzz__LegacyResourcesProvider_def.hpp"
#include "UnityEngine/ResourceManagement/ResourceProviders/zzzz__LegacyResourcesProvider_impl.hpp"
