#pragma once
#include "UnityEngine/ResourceManagement/ResourceProviders/zzzz__SceneProviderExtensions_def.hpp"
#include "UnityEngine/ResourceManagement/ResourceProviders/zzzz__SceneProviderExtensions_impl.hpp"
