#pragma once
#include "System/ComponentModel/Design/CheckoutException.hpp"
#include "System/ComponentModel/Design/IComponentChangeService.hpp"
#include "System/ComponentModel/Design/IDesigner.hpp"
#include "System/ComponentModel/Design/IDesignerHost.hpp"
#include "System/ComponentModel/Design/IDictionaryService.hpp"
#include "System/ComponentModel/Design/IExtenderListService.hpp"
#include "System/ComponentModel/Design/IReferenceService.hpp"
#include "System/ComponentModel/Design/ITypeDescriptorFilterService.hpp"