// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: Org.BouncyCastle.Crypto.Parameters.KdfParameters
#include "Org/BouncyCastle/Crypto/Parameters/KdfParameters.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated method: Org.BouncyCastle.Crypto.Parameters.KdfParameters..ctor
Org::BouncyCastle::Crypto::Parameters::KdfParameters* Org::BouncyCastle::Crypto::Parameters::KdfParameters::New_ctor(::Array<uint8_t>* shared, ::Array<uint8_t>* iv) {
  static auto ___internal__logger = ::Logger::get().WithContext("codegen").WithContext("Org::BouncyCastle::Crypto::Parameters").WithContext("KdfParameters").WithContext(".ctor");
  return THROW_UNLESS(::il2cpp_utils::New<KdfParameters*>(shared, iv));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Parameters.KdfParameters.GetSharedSecret
::Array<uint8_t>* Org::BouncyCastle::Crypto::Parameters::KdfParameters::GetSharedSecret() {
  static auto ___internal__logger = ::Logger::get().WithContext("codegen").WithContext("Org::BouncyCastle::Crypto::Parameters").WithContext("KdfParameters").WithContext("GetSharedSecret");
  static auto* ___internal__method = THROW_UNLESS(::il2cpp_utils::FindMethod(this, il2cpp_utils::NoArgClass<::Array<uint8_t>*>(), "GetSharedSecret", {}, ::il2cpp_utils::ExtractTypes()));
  return ::il2cpp_utils::RunMethodThrow<::Array<uint8_t>*, false>(this, ___internal__method);
}
// Autogenerated method: Org.BouncyCastle.Crypto.Parameters.KdfParameters.GetIV
::Array<uint8_t>* Org::BouncyCastle::Crypto::Parameters::KdfParameters::GetIV() {
  static auto ___internal__logger = ::Logger::get().WithContext("codegen").WithContext("Org::BouncyCastle::Crypto::Parameters").WithContext("KdfParameters").WithContext("GetIV");
  static auto* ___internal__method = THROW_UNLESS(::il2cpp_utils::FindMethod(this, il2cpp_utils::NoArgClass<::Array<uint8_t>*>(), "GetIV", {}, ::il2cpp_utils::ExtractTypes()));
  return ::il2cpp_utils::RunMethodThrow<::Array<uint8_t>*, false>(this, ___internal__method);
}
