// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
// Including type: LiteNetLib.NatAddressType
#include "LiteNetLib/NatAddressType.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated static field getter
// Get static field: static public LiteNetLib.NatAddressType Internal
LiteNetLib::NatAddressType LiteNetLib::NatAddressType::_get_Internal() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<LiteNetLib::NatAddressType>("LiteNetLib", "NatAddressType", "Internal"));
}
// Autogenerated static field setter
// Set static field: static public LiteNetLib.NatAddressType Internal
void LiteNetLib::NatAddressType::_set_Internal(LiteNetLib::NatAddressType value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("LiteNetLib", "NatAddressType", "Internal", value));
}
// Autogenerated static field getter
// Get static field: static public LiteNetLib.NatAddressType External
LiteNetLib::NatAddressType LiteNetLib::NatAddressType::_get_External() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<LiteNetLib::NatAddressType>("LiteNetLib", "NatAddressType", "External"));
}
// Autogenerated static field setter
// Set static field: static public LiteNetLib.NatAddressType External
void LiteNetLib::NatAddressType::_set_External(LiteNetLib::NatAddressType value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("LiteNetLib", "NatAddressType", "External", value));
}
