// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities
#include "Org/BouncyCastle/Crypto/Modes/Gcm/GcmUtilities.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated static field getter
// Get static field: static private readonly System.UInt32[] LOOKUP
::Array<uint>* Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::_get_LOOKUP() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<::Array<uint>*>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "LOOKUP"));
}
// Autogenerated static field setter
// Set static field: static private readonly System.UInt32[] LOOKUP
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::_set_LOOKUP(::Array<uint>* value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "LOOKUP", value));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.GenerateLookup
::Array<uint>* Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::GenerateLookup() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Array<uint>*>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "GenerateLookup"));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.OneAsUints
::Array<uint>* Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::OneAsUints() {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Array<uint>*>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "OneAsUints"));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.AsBytes
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::AsBytes(::Array<uint>* x, ::Array<uint8_t>* z) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "AsBytes", x, z));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.AsUints
::Array<uint>* Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::AsUints(::Array<uint8_t>* bs) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<::Array<uint>*>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "AsUints", bs));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Multiply
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Multiply(::Array<uint8_t>* x, ::Array<uint8_t>* y) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Multiply", x, y));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Multiply
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Multiply(::Array<uint>* x, ::Array<uint>* y) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Multiply", x, y));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.MultiplyP
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::MultiplyP(::Array<uint>* x) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "MultiplyP", x));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.MultiplyP8
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::MultiplyP8(::Array<uint>* x) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "MultiplyP8", x));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.ShiftRight
uint Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::ShiftRight(::Array<uint>* x) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<uint>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "ShiftRight", x));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.ShiftRightN
uint Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::ShiftRightN(::Array<uint>* x, int n) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<uint>("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "ShiftRightN", x, n));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint8_t>* x, ::Array<uint8_t>* y) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, y));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint8_t>* x, ::Array<uint8_t>* y, int yOff) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, y, yOff));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint8_t>* x, int xOff, ::Array<uint8_t>* y, int yOff, ::Array<uint8_t>* z, int zOff) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, xOff, y, yOff, z, zOff));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint8_t>* x, ::Array<uint8_t>* y, int yOff, int yLen) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, y, yOff, yLen));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint8_t>* x, int xOff, ::Array<uint8_t>* y, int yOff, int len) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, xOff, y, yOff, len));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities.Xor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::Xor(::Array<uint>* x, ::Array<uint>* y) {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", "Xor", x, y));
}
// Autogenerated method: Org.BouncyCastle.Crypto.Modes.Gcm.GcmUtilities..cctor
void Org::BouncyCastle::Crypto::Modes::Gcm::GcmUtilities::_cctor() {
  THROW_UNLESS(il2cpp_utils::RunMethod("Org.BouncyCastle.Crypto.Modes.Gcm", "GcmUtilities", ".cctor"));
}
