// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: System.Attribute
#include "System/Attribute.hpp"
// Completed includes
// Type namespace: Il2CppDummyDll
namespace Il2CppDummyDll {
  // Autogenerated type: Il2CppDummyDll.FieldOffsetAttribute
  class FieldOffsetAttribute : public System::Attribute {
    public:
    // public System.String Offset
    // Offset: 0xFFFFFFFF
    ::Il2CppString* Offset;
    // Creating conversion operator: operator ::Il2CppString*
    constexpr operator ::Il2CppString*() const noexcept {
      return Offset;
    }
    // public System.Void .ctor()
    // Offset: 0xFFFFFFFF
    // Implemented from: System.Attribute
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static FieldOffsetAttribute* New_ctor();
  }; // Il2CppDummyDll.FieldOffsetAttribute
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(Il2CppDummyDll::FieldOffsetAttribute*, "Il2CppDummyDll", "FieldOffsetAttribute");
#pragma pack(pop)
