// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: System.IO.SeekOrigin
#include "System/IO/SeekOrigin.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated static field getter
// Get static field: static public System.IO.SeekOrigin Begin
System::IO::SeekOrigin System::IO::SeekOrigin::_get_Begin() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::IO::SeekOrigin>("System.IO", "SeekOrigin", "Begin"));
}
// Autogenerated static field setter
// Set static field: static public System.IO.SeekOrigin Begin
void System::IO::SeekOrigin::_set_Begin(System::IO::SeekOrigin value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.IO", "SeekOrigin", "Begin", value));
}
// Autogenerated static field getter
// Get static field: static public System.IO.SeekOrigin Current
System::IO::SeekOrigin System::IO::SeekOrigin::_get_Current() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::IO::SeekOrigin>("System.IO", "SeekOrigin", "Current"));
}
// Autogenerated static field setter
// Set static field: static public System.IO.SeekOrigin Current
void System::IO::SeekOrigin::_set_Current(System::IO::SeekOrigin value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.IO", "SeekOrigin", "Current", value));
}
// Autogenerated static field getter
// Get static field: static public System.IO.SeekOrigin End
System::IO::SeekOrigin System::IO::SeekOrigin::_get_End() {
  return THROW_UNLESS(il2cpp_utils::GetFieldValue<System::IO::SeekOrigin>("System.IO", "SeekOrigin", "End"));
}
// Autogenerated static field setter
// Set static field: static public System.IO.SeekOrigin End
void System::IO::SeekOrigin::_set_End(System::IO::SeekOrigin value) {
  THROW_UNLESS(il2cpp_utils::SetFieldValue("System.IO", "SeekOrigin", "End", value));
}
