// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Org::BouncyCastle::Asn1
namespace Org::BouncyCastle::Asn1 {
  // Forward declaring type: DerObjectIdentifier
  class DerObjectIdentifier;
}
// Completed forward declares
// Type namespace: Org.BouncyCastle.Asn1.Ntt
namespace Org::BouncyCastle::Asn1::Ntt {
  // Autogenerated type: Org.BouncyCastle.Asn1.Ntt.NttObjectIdentifiers
  class NttObjectIdentifiers : public ::Il2CppObject {
    public:
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia128Cbc
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia128Cbc();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia128Cbc
    static void _set_IdCamellia128Cbc(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia192Cbc
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia192Cbc();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia192Cbc
    static void _set_IdCamellia192Cbc(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia256Cbc
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia256Cbc();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia256Cbc
    static void _set_IdCamellia256Cbc(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia128Wrap
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia128Wrap();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia128Wrap
    static void _set_IdCamellia128Wrap(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia192Wrap
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia192Wrap();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia192Wrap
    static void _set_IdCamellia192Wrap(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // Get static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia256Wrap
    static Org::BouncyCastle::Asn1::DerObjectIdentifier* _get_IdCamellia256Wrap();
    // Set static field: static public readonly Org.BouncyCastle.Asn1.DerObjectIdentifier IdCamellia256Wrap
    static void _set_IdCamellia256Wrap(Org::BouncyCastle::Asn1::DerObjectIdentifier* value);
    // static private System.Void .cctor()
    // Offset: 0x14064BC
    static void _cctor();
  }; // Org.BouncyCastle.Asn1.Ntt.NttObjectIdentifiers
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(Org::BouncyCastle::Asn1::Ntt::NttObjectIdentifiers*, "Org.BouncyCastle.Asn1.Ntt", "NttObjectIdentifiers");
#pragma pack(pop)
