// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: IntPtr
  struct IntPtr;
}
// Completed forward declares
// Type namespace: Oculus.Platform.Models
namespace Oculus::Platform::Models {
  // Autogenerated type: Oculus.Platform.Models.UserReportID
  class UserReportID : public ::Il2CppObject {
    public:
    // public readonly System.Boolean DidCancel
    // Offset: 0x10
    bool DidCancel;
    // public readonly System.UInt64 ID
    // Offset: 0x18
    uint64_t ID;
    // public System.Void .ctor(System.IntPtr o)
    // Offset: 0xEA9EE0
    static UserReportID* New_ctor(System::IntPtr o);
  }; // Oculus.Platform.Models.UserReportID
}
#include "extern/beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(Oculus::Platform::Models::UserReportID*, "Oculus.Platform.Models", "UserReportID");
#pragma pack(pop)
