// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
// Including type: BloomPrePassBackgroundGradient
#include "GlobalNamespace/BloomPrePassBackgroundGradient.hpp"
// Including type: UnityEngine.Gradient
#include "UnityEngine/Gradient.hpp"
// Including type: Unity.Collections.NativeArray`1
#include "Unity/Collections/NativeArray_1.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated method: BloomPrePassBackgroundGradient.UpdatePixels
void GlobalNamespace::BloomPrePassBackgroundGradient::UpdatePixels(Unity::Collections::NativeArray_1<UnityEngine::Color32> pixels, int numberOfPixels) {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "UpdatePixels", pixels, numberOfPixels));
}
// Autogenerated method: BloomPrePassBackgroundGradient..ctor
GlobalNamespace::BloomPrePassBackgroundGradient* GlobalNamespace::BloomPrePassBackgroundGradient::New_ctor() {
  return THROW_UNLESS(il2cpp_utils::New<BloomPrePassBackgroundGradient*>());
}
