// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
// Including type: MenuRpcManager/SetIsInLobbyRpc
#include "GlobalNamespace/MenuRpcManager_SetIsInLobbyRpc.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated method: MenuRpcManager/SetIsInLobbyRpc..ctor
GlobalNamespace::MenuRpcManager::SetIsInLobbyRpc* GlobalNamespace::MenuRpcManager::SetIsInLobbyRpc::New_ctor() {
  static auto ___internal__logger = ::Logger::get().WithContext("codegen").WithContext("GlobalNamespace").WithContext("SetIsInLobbyRpc").WithContext(".ctor");
  return THROW_UNLESS(::il2cpp_utils::New<MenuRpcManager::SetIsInLobbyRpc*>());
}
