// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
// Including type: UserLoginDtoDataSource/<GetUserAuthToken>d__7
#include "GlobalNamespace/UserLoginDtoDataSource_-GetUserAuthToken-d__7.hpp"
// Including type: PlatformTokenInfo
#include "GlobalNamespace/PlatformTokenInfo.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated method: UserLoginDtoDataSource/<GetUserAuthToken>d__7.MoveNext
void GlobalNamespace::UserLoginDtoDataSource::$GetUserAuthToken$d__7::MoveNext() {
  THROW_UNLESS(il2cpp_utils::RunMethod(*this, "MoveNext"));
}
// Autogenerated method: UserLoginDtoDataSource/<GetUserAuthToken>d__7.SetStateMachine
void GlobalNamespace::UserLoginDtoDataSource::$GetUserAuthToken$d__7::SetStateMachine(System::Runtime::CompilerServices::IAsyncStateMachine* stateMachine) {
  THROW_UNLESS(il2cpp_utils::RunMethod(*this, "SetStateMachine", stateMachine));
}
