#pragma once
#include "UnityEngine/SceneManagement/LoadSceneMode.hpp"
#include "UnityEngine/SceneManagement/LoadSceneParameters.hpp"
#include "UnityEngine/SceneManagement/LocalPhysicsMode.hpp"
#include "UnityEngine/SceneManagement/Scene.hpp"
#include "UnityEngine/SceneManagement/SceneManager.hpp"
#include "UnityEngine/SceneManagement/SceneManagerAPI.hpp"
#include "UnityEngine/SceneManagement/SceneManagerAPIInternal.hpp"
#include "UnityEngine/SceneManagement/UnloadSceneOptions.hpp"