// Autogenerated from CppSourceCreator
// Created by Sc2ad
// =========================================================================
// Begin includes
#include "extern/beatsaber-hook/shared/utils/typedefs.h"
// Including type: Valve.VR.IVRCompositor/_CompositorBringToFront
#include "Valve/VR/IVRCompositor__CompositorBringToFront.hpp"
// Including type: System.IAsyncResult
#include "System/IAsyncResult.hpp"
// Including type: System.AsyncCallback
#include "System/AsyncCallback.hpp"
#include "extern/beatsaber-hook/shared/utils/il2cpp-utils.hpp"
#include "extern/beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Autogenerated method: Valve.VR.IVRCompositor/_CompositorBringToFront..ctor
Valve::VR::IVRCompositor::_CompositorBringToFront* Valve::VR::IVRCompositor::_CompositorBringToFront::New_ctor(::Il2CppObject* object, System::IntPtr method) {
  return THROW_UNLESS(il2cpp_utils::New<IVRCompositor::_CompositorBringToFront*>(object, method));
}
// Autogenerated method: Valve.VR.IVRCompositor/_CompositorBringToFront.Invoke
void Valve::VR::IVRCompositor::_CompositorBringToFront::Invoke() {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "Invoke"));
}
// Autogenerated method: Valve.VR.IVRCompositor/_CompositorBringToFront.BeginInvoke
System::IAsyncResult* Valve::VR::IVRCompositor::_CompositorBringToFront::BeginInvoke(System::AsyncCallback* callback, ::Il2CppObject* object) {
  return THROW_UNLESS(il2cpp_utils::RunMethod<System::IAsyncResult*>(this, "BeginInvoke", callback, object));
}
// Autogenerated method: Valve.VR.IVRCompositor/_CompositorBringToFront.EndInvoke
void Valve::VR::IVRCompositor::_CompositorBringToFront::EndInvoke(System::IAsyncResult* result) {
  THROW_UNLESS(il2cpp_utils::RunMethod(this, "EndInvoke", result));
}
