#pragma once
#include "UnityEngine/ResourceManagement/Exceptions/zzzz__UnknownResourceProviderException_def.hpp"
#include "UnityEngine/ResourceManagement/Exceptions/zzzz__UnknownResourceProviderException_impl.hpp"
